[tool.poetry]
name = "medical-lay"
version = "0.1.0"
description = ""
authors = ["tpatzelt <tpatzelt@uos.de>"]
readme = "README.md"
packages = [{ include = "medical_lay" }]

[tool.poetry.dependencies]
python = "^3.11"
jupyter = "^1.0.0"
requests = "^2.28.2"
pydantic = "^1.10.4"
tqdm = "^4.64.1"
pandas = "^1.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
